# Generated by Django 2.0.1 on 2018-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='creation_timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
